package model.pojos;
// Generated 11/10/2012 10:56:45 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idEmpleado;
     private EstatusEmpleado estatusEmpleado;
     private Rol rol;
     private String primerNombre;
     private String segundoNombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String usuario;
     private String password;
     private Set empleados = new HashSet(0);
     private Set historiaCarteras = new HashSet(0);
     private Set jefes = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int idEmpleado, Rol rol) {
        this.idEmpleado = idEmpleado;
        this.rol = rol;
    }
    public Empleado(int idEmpleado, EstatusEmpleado estatusEmpleado, Rol rol, String primerNombre, String segundoNombre, String apellidoPaterno, String apellidoMaterno, String usuario, String password, Set jerarquiaEmpleadosForIdJefe, Set historiaCarteras, Set jerarquiaEmpleadosForIdEmpleado) {
       this.idEmpleado = idEmpleado;
       this.estatusEmpleado = estatusEmpleado;
       this.rol = rol;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.usuario = usuario;
       this.password = password;
       this.empleados = jerarquiaEmpleadosForIdJefe;
       this.historiaCarteras = historiaCarteras;
       this.jefes = jerarquiaEmpleadosForIdEmpleado;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public EstatusEmpleado getEstatusEmpleado() {
        return this.estatusEmpleado;
    }
    
    public void setEstatusEmpleado(EstatusEmpleado estatusEmpleado) {
        this.estatusEmpleado = estatusEmpleado;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    
    //idjefe
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getHistoriaCarteras() {
        return this.historiaCarteras;
    }
    
    public void setHistoriaCarteras(Set historiaCarteras) {
        this.historiaCarteras = historiaCarteras;
    }
    public Set getJefes() {
        return this.jefes;
    }
    
    public void setJefes(Set jefes) {
        this.jefes = jefes;
    }

    /**
     * metodo que nos sirve para obtener todos los empleados en cualquier jerarquia
     * @return 
     */
    public Set getAllEmpleados(){
        Set<Empleado> conjunto=new HashSet<Empleado>();
        buscarEmpleados(conjunto,this);
        return conjunto;
    }

    /**
     * metodo que busca recursivamente a todos los empleados 
     * @param conjunto
     * @param empleado 
     */
    private void buscarEmpleados(Set<Empleado> conjunto, Empleado empleado) {
        Set<JerarquiaEmpleado> directos  = empleado.getEmpleados();
        for(JerarquiaEmpleado jer:directos){
            conjunto.add(jer.getEmpleadoByIdEmpleado());
            buscarEmpleados(conjunto, jer.getEmpleadoByIdEmpleado());
        }
    }



}






