package model.pojos;
// Generated 11/10/2012 12:23:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EstatusVivienda generated by hbm2java
 */
public class EstatusVivienda  implements java.io.Serializable {


     private int idEstatusVivienda;
     private String desEstatusVivienda;
     private Set viviendas = new HashSet(0);

    public EstatusVivienda() {
    }

	
    public EstatusVivienda(int idEstatusVivienda) {
        this.idEstatusVivienda = idEstatusVivienda;
    }
    public EstatusVivienda(int idEstatusVivienda, String desEstatusVivienda, Set viviendas) {
       this.idEstatusVivienda = idEstatusVivienda;
       this.desEstatusVivienda = desEstatusVivienda;
       this.viviendas = viviendas;
    }
   
    public int getIdEstatusVivienda() {
        return this.idEstatusVivienda;
    }
    
    public void setIdEstatusVivienda(int idEstatusVivienda) {
        this.idEstatusVivienda = idEstatusVivienda;
    }
    public String getDesEstatusVivienda() {
        return this.desEstatusVivienda;
    }
    
    public void setDesEstatusVivienda(String desEstatusVivienda) {
        this.desEstatusVivienda = desEstatusVivienda;
    }
    public Set getViviendas() {
        return this.viviendas;
    }
    
    public void setViviendas(Set viviendas) {
        this.viviendas = viviendas;
    }




}


