package model.pojos;
// Generated 11/10/2012 12:23:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EstatusCliente generated by hbm2java
 */
public class EstatusCliente  implements java.io.Serializable {


     private int idEstatusCliente;
     private String desEstatusCliente;
     private Set clientes = new HashSet(0);

    public EstatusCliente() {
    }

	
    public EstatusCliente(int idEstatusCliente) {
        this.idEstatusCliente = idEstatusCliente;
    }
    public EstatusCliente(int idEstatusCliente, String desEstatusCliente, Set clientes) {
       this.idEstatusCliente = idEstatusCliente;
       this.desEstatusCliente = desEstatusCliente;
       this.clientes = clientes;
    }
   
    public int getIdEstatusCliente() {
        return this.idEstatusCliente;
    }
    
    public void setIdEstatusCliente(int idEstatusCliente) {
        this.idEstatusCliente = idEstatusCliente;
    }
    public String getDesEstatusCliente() {
        return this.desEstatusCliente;
    }
    
    public void setDesEstatusCliente(String desEstatusCliente) {
        this.desEstatusCliente = desEstatusCliente;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


