package model.pojos;
// Generated 11/10/2012 12:23:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EstatusCartera generated by hbm2java
 */
public class EstatusCartera  implements java.io.Serializable {


     private int idEstatusCartera;
     private String desEstatusCartera;
     private Set historiaCarteras = new HashSet(0);

    public EstatusCartera() {
    }

	
    public EstatusCartera(int idEstatusCartera) {
        this.idEstatusCartera = idEstatusCartera;
    }
    public EstatusCartera(int idEstatusCartera, String desEstatusCartera, Set historiaCarteras) {
       this.idEstatusCartera = idEstatusCartera;
       this.desEstatusCartera = desEstatusCartera;
       this.historiaCarteras = historiaCarteras;
    }
   
    public int getIdEstatusCartera() {
        return this.idEstatusCartera;
    }
    
    public void setIdEstatusCartera(int idEstatusCartera) {
        this.idEstatusCartera = idEstatusCartera;
    }
    public String getDesEstatusCartera() {
        return this.desEstatusCartera;
    }
    
    public void setDesEstatusCartera(String desEstatusCartera) {
        this.desEstatusCartera = desEstatusCartera;
    }
    public Set getHistoriaCarteras() {
        return this.historiaCarteras;
    }
    
    public void setHistoriaCarteras(Set historiaCarteras) {
        this.historiaCarteras = historiaCarteras;
    }




}


