package model.pojos;
// Generated 11/10/2012 12:23:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HistoriaCartera generated by hbm2java
 */
public class HistoriaCartera  implements java.io.Serializable {


     private Integer idHistoriaCartera;
     private Empleado empleado;
     private EstatusCartera estatusCartera;
     private Cliente cliente;
     private int ordenHistorico;
     private Date fechaEntrada;
     private Date fechaSalida;
     private Set historiaConvenios = new HashSet(0);
     private Set historiaPagoses = new HashSet(0);

    public HistoriaCartera() {
    }

	
    public HistoriaCartera(Cliente cliente, int ordenHistorico) {
        this.cliente = cliente;
        this.ordenHistorico = ordenHistorico;
    }
    public HistoriaCartera(Empleado empleado, EstatusCartera estatusCartera, Cliente cliente, int ordenHistorico, Date fechaEntrada, Date fechaSalida, Set historiaConvenios, Set historiaPagoses) {
       this.empleado = empleado;
       this.estatusCartera = estatusCartera;
       this.cliente = cliente;
       this.ordenHistorico = ordenHistorico;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.historiaConvenios = historiaConvenios;
       this.historiaPagoses = historiaPagoses;
    }
   
    public Integer getIdHistoriaCartera() {
        return this.idHistoriaCartera;
    }
    
    public void setIdHistoriaCartera(Integer idHistoriaCartera) {
        this.idHistoriaCartera = idHistoriaCartera;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public EstatusCartera getEstatusCartera() {
        return this.estatusCartera;
    }
    
    public void setEstatusCartera(EstatusCartera estatusCartera) {
        this.estatusCartera = estatusCartera;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public int getOrdenHistorico() {
        return this.ordenHistorico;
    }
    
    public void setOrdenHistorico(int ordenHistorico) {
        this.ordenHistorico = ordenHistorico;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public Set getHistoriaConvenios() {
        return this.historiaConvenios;
    }
    
    public void setHistoriaConvenios(Set historiaConvenios) {
        this.historiaConvenios = historiaConvenios;
    }
    public Set getHistoriaPagoses() {
        return this.historiaPagoses;
    }
    
    public void setHistoriaPagoses(Set historiaPagoses) {
        this.historiaPagoses = historiaPagoses;
    }




}


