package model.pojos;
// Generated 11/10/2012 12:23:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HistoriaConvenio generated by hbm2java
 */
public class HistoriaConvenio  implements java.io.Serializable {


     private Integer idHistoriaConvenio;
     private EstatusConvenio estatusConvenio;
     private HistoriaCartera historiaCartera;
     private Date fechaCreacion;
     private Date fechaCompromiso;
     private double monto;

    public HistoriaConvenio() {
    }

    public HistoriaConvenio(EstatusConvenio estatusConvenio, HistoriaCartera historiaCartera, Date fechaCreacion, Date fechaCompromiso, double monto) {
       this.estatusConvenio = estatusConvenio;
       this.historiaCartera = historiaCartera;
       this.fechaCreacion = fechaCreacion;
       this.fechaCompromiso = fechaCompromiso;
       this.monto = monto;
    }
   
    public Integer getIdHistoriaConvenio() {
        return this.idHistoriaConvenio;
    }
    
    public void setIdHistoriaConvenio(Integer idHistoriaConvenio) {
        this.idHistoriaConvenio = idHistoriaConvenio;
    }
    public EstatusConvenio getEstatusConvenio() {
        return this.estatusConvenio;
    }
    
    public void setEstatusConvenio(EstatusConvenio estatusConvenio) {
        this.estatusConvenio = estatusConvenio;
    }
    public HistoriaCartera getHistoriaCartera() {
        return this.historiaCartera;
    }
    
    public void setHistoriaCartera(HistoriaCartera historiaCartera) {
        this.historiaCartera = historiaCartera;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaCompromiso() {
        return this.fechaCompromiso;
    }
    
    public void setFechaCompromiso(Date fechaCompromiso) {
        this.fechaCompromiso = fechaCompromiso;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }




}


