package model.pojos;
// Generated 11/10/2012 12:23:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HistoriaPagos generated by hbm2java
 */
public class HistoriaPagos  implements java.io.Serializable {


     private Integer idHistoriaPagos;
     private HistoriaCartera historiaCartera;
     private Date fechaPago;
     private double monto;

    public HistoriaPagos() {
    }

    public HistoriaPagos(HistoriaCartera historiaCartera, Date fechaPago, double monto) {
       this.historiaCartera = historiaCartera;
       this.fechaPago = fechaPago;
       this.monto = monto;
    }
   
    public Integer getIdHistoriaPagos() {
        return this.idHistoriaPagos;
    }
    
    public void setIdHistoriaPagos(Integer idHistoriaPagos) {
        this.idHistoriaPagos = idHistoriaPagos;
    }
    public HistoriaCartera getHistoriaCartera() {
        return this.historiaCartera;
    }
    
    public void setHistoriaCartera(HistoriaCartera historiaCartera) {
        this.historiaCartera = historiaCartera;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }




}


