package model.pojos;
// Generated 11/10/2012 12:23:06 PM by Hibernate Tools 3.2.1.GA



/**
 * JerarquiaEmpleado generated by hbm2java
 */
public class JerarquiaEmpleado  implements java.io.Serializable {


     private Integer idJerarquiaEmpleado;
     private Empleado empleadoByIdEmpleado;
     private Empleado empleadoByIdJefe;

    public JerarquiaEmpleado() {
    }

    public JerarquiaEmpleado(Empleado empleadoByIdEmpleado, Empleado empleadoByIdJefe) {
       this.empleadoByIdEmpleado = empleadoByIdEmpleado;
       this.empleadoByIdJefe = empleadoByIdJefe;
    }
   
    public Integer getIdJerarquiaEmpleado() {
        return this.idJerarquiaEmpleado;
    }
    
    public void setIdJerarquiaEmpleado(Integer idJerarquiaEmpleado) {
        this.idJerarquiaEmpleado = idJerarquiaEmpleado;
    }
    public Empleado getEmpleadoByIdEmpleado() {
        return this.empleadoByIdEmpleado;
    }
    
    public void setEmpleadoByIdEmpleado(Empleado empleadoByIdEmpleado) {
        this.empleadoByIdEmpleado = empleadoByIdEmpleado;
    }
    public Empleado getEmpleadoByIdJefe() {
        return this.empleadoByIdJefe;
    }
    
    public void setEmpleadoByIdJefe(Empleado empleadoByIdJefe) {
        this.empleadoByIdJefe = empleadoByIdJefe;
    }




}


