package model.pojos;
// Generated 11/10/2012 12:23:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int idRol;
     private String desRol;
     private Set empleados = new HashSet(0);

    public Rol() {
    }

	
    public Rol(int idRol) {
        this.idRol = idRol;
    }
    public Rol(int idRol, String desRol, Set empleados) {
       this.idRol = idRol;
       this.desRol = desRol;
       this.empleados = empleados;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getDesRol() {
        return this.desRol;
    }
    
    public void setDesRol(String desRol) {
        this.desRol = desRol;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


