package model.pojos;
// Generated 11/10/2012 12:23:06 PM by Hibernate Tools 3.2.1.GA



/**
 * Vivienda generated by hbm2java
 */
public class Vivienda  implements java.io.Serializable {


     private Integer idVivienda;
     private EstatusVivienda estatusVivienda;
     private Cliente cliente;
     private Integer posicionLatitud;
     private Integer posicionLongitud;
     private String direccionCalle;
     private String direccionNumero;
     private String direccionColonia;
     private String direccionDelegacionMunicipio;
     private Integer direccionCodigoPostal;

    public Vivienda() {
    }

	
    public Vivienda(Cliente cliente) {
        this.cliente = cliente;
    }
    public Vivienda(EstatusVivienda estatusVivienda, Cliente cliente, Integer posicionLatitud, Integer posicionLongitud, String direccionCalle, String direccionNumero, String direccionColonia, String direccionDelegacionMunicipio, Integer direccionCodigoPostal) {
       this.estatusVivienda = estatusVivienda;
       this.cliente = cliente;
       this.posicionLatitud = posicionLatitud;
       this.posicionLongitud = posicionLongitud;
       this.direccionCalle = direccionCalle;
       this.direccionNumero = direccionNumero;
       this.direccionColonia = direccionColonia;
       this.direccionDelegacionMunicipio = direccionDelegacionMunicipio;
       this.direccionCodigoPostal = direccionCodigoPostal;
    }
   
    public Integer getIdVivienda() {
        return this.idVivienda;
    }
    
    public void setIdVivienda(Integer idVivienda) {
        this.idVivienda = idVivienda;
    }
    public EstatusVivienda getEstatusVivienda() {
        return this.estatusVivienda;
    }
    
    public void setEstatusVivienda(EstatusVivienda estatusVivienda) {
        this.estatusVivienda = estatusVivienda;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Integer getPosicionLatitud() {
        return this.posicionLatitud;
    }
    
    public void setPosicionLatitud(Integer posicionLatitud) {
        this.posicionLatitud = posicionLatitud;
    }
    public Integer getPosicionLongitud() {
        return this.posicionLongitud;
    }
    
    public void setPosicionLongitud(Integer posicionLongitud) {
        this.posicionLongitud = posicionLongitud;
    }
    public String getDireccionCalle() {
        return this.direccionCalle;
    }
    
    public void setDireccionCalle(String direccionCalle) {
        this.direccionCalle = direccionCalle;
    }
    public String getDireccionNumero() {
        return this.direccionNumero;
    }
    
    public void setDireccionNumero(String direccionNumero) {
        this.direccionNumero = direccionNumero;
    }
    public String getDireccionColonia() {
        return this.direccionColonia;
    }
    
    public void setDireccionColonia(String direccionColonia) {
        this.direccionColonia = direccionColonia;
    }
    public String getDireccionDelegacionMunicipio() {
        return this.direccionDelegacionMunicipio;
    }
    
    public void setDireccionDelegacionMunicipio(String direccionDelegacionMunicipio) {
        this.direccionDelegacionMunicipio = direccionDelegacionMunicipio;
    }
    public Integer getDireccionCodigoPostal() {
        return this.direccionCodigoPostal;
    }
    
    public void setDireccionCodigoPostal(Integer direccionCodigoPostal) {
        this.direccionCodigoPostal = direccionCodigoPostal;
    }




}


